lua/hover/actions.lua

:wave:
This adds a gate for the window title functionality so that the plugin can degrade gracefully, since this is an unreleased nvim feature.
I see that the winbar thing was a [recent change](8985eb1). It _might_ be preferable to revert to the old behavior for nvim <0.8 instead of giving up entirely, but I didn't really feel like implementing all of that for something so minor, especially since nvim 0.8 should drop pretty soon.
I'm not a lua noob, but I _am_ a neovim noob, so feel free to correct me on any of this :) And thanks for making this plugin!

fix: add feature detection for winbar

---

lua/hover/actions.lua
lua/hover/providers.lua

I found it a bit disrupting that these particular logs showed up in my
message history, figured it'd make sense to use nvim_echo for this
instead?
Also changed remaining print() to vim.notify() with an appropriate log
level.

fix: use nvim_echo to avoid polluting message-history

---

lua/hover/actions.lua

The floating window will, by default, have the same size as the amount of lines
in the contents provided to `vim.lsp.util.open_floating_preview`. When setting a winbar
it'll offset the contents by one line cause it to overflow the window height, effectively hiding
the last line.

fix: increase window height when injecting title line

---

lua/hover/actions.lua

When the contents of the floating window is short (horizontally), the winbar will overflow and be cut off. This ensures the floating window is always at least wide enough to cover the winbar.
Before:
After:

fix: ensure floating window can fit winbar without overflowing

---

lua/hover/providers/jira.lua

At the moment having 'ABC-66:' (for example) is getting through the 'enabled' check but not through the 'execute' because the match is not done there (removing the ':').

fix: Jira provider match not being done in execute

---

lua/hover/actions.lua

Bugfix:
- `pwin_prev_buf` is not a valid bufnr if sending content to preview window when preview window is already opened

Prevent focus moving to preview window and bugfix

---

lua/hover/providers/gh.lua

Github username can contain `-` and repo name can contain `-`, `_` and `.`.

fix: `gh` repo pattern

---

lua/hover/actions.lua
lua/hover/async/job.lua
lua/hover/providers/gh.lua
lua/hover/providers/gh_user.lua

PROBLEM: No error message or barely helpful error messages, such as
`Failed to parse gh result` (which is usually a 404 error, actually).
SOLUTION: Extract stderr of the spawned job process and notify users
the result is nil (e.g., when process failed to launch, exit with
non-zero error code with some error messages).
Example:
- gh: `not-existent-user/404-repo#12345`
Before: `Failed to parse gh result`
After: Show error message
```
GraphQL: Could not resolve to a Repository with the name
'not-existent-user/404-repo'. (repository)
```
- gh: `#99990000` (invalid issue number)
Before: `Failed to parse gh user result`
After: Show error message
```
GraphQL: Could not resolve to an issue or pull request with the
number of 99990000. (repository.issue)
```
- gh_user: …

fix: Handle errors and notify users if results can't be retrieved

---

lua/hover/actions.lua

Had the same error as described in the issue, this should fix it.
Resolves: #47

fix hover_select: use current buf as default when checking is_enabled

---

lua/hover/util.lua

Hey, I get an error complaining about height=nan if LSP is returning empty documentation (which happens occasionally with JDTLS). This should fix it.

fix: fix divide by zero if content is empty

---

README.md
lua/hover.lua
lua/hover/actions.lua

I added a function `hover_switch` that toggles to the next/previous Hover provider in the current window, along with example keybinds in the readme. This was mostly for my own sake, as it was a feature that I thought would be nice to have, but it should also resolve #15.

Add `hover_switch` function and associated documentation

---

lua/hover/actions.lua

ref: https://github.com/lewis6991/hover.nvim/pull/51 (closed when resetting my branch)
- Fix buffer retrieval when hovering a non-active window.
- delay previous hover close on mouse move, thus allowing the user to move his mouse pointer onto the hover window and then scroll or click to focus.

find buffer by window on mouse-hover

---

lua/hover/providers/lsp.lua

When showing hover information when the LSP is ccls, the plugin returns an error. This PR fixes it.

fix(lsp): fix utf-32 being considered as invalid encoding

---

README.md
lua/hover/providers/dap.lua

Slightly hacky way to integrate [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) hover. The session API is async, so in order to support resizing and interactivity, DAP binds a window id to view. Instead of this I search for a window containing the buffer on update to resize it.

feat: add DAP provider

---

lua/hover/providers/dap.lua

I have been using the dap hover for a while and noticed that it does not delete the buffer on close, searching for a window to resize. As I said, someone should allow to manage the window, either hover.nvim or nvim-dap to implement this hover without ugly copypasta. Here is temporary workaround to fix dap completely breaking hover if the session is closed.
Tested it on python dap with following steps:
1. Open some python script
2. Put a breakpoint somewhere
3. (Optional) Perform hover with LSP
4. Launch Debug session
5. Perform hover with DAP
6. Terminate the session
7. Try to perform hover again (DAP was breaking this step)
The PR is marked as draft because the buffer is not deleted when closing the DAP hover and ending session. That could be the inacceptable behavior
Also the previous …

bug(dap): hover breaks after ended dap session

---

README.md
lua/hover/providers/dap.lua
lua/hover/providers/diagnostic.lua
lua/hover/util.lua

Adds a provider for diagnostics. Mostly taken from `vim.diagnostic.show_float`, with some tweaks.
Options from `vim.diagnostic.config` are used for float opts like `scope` and `severity_sort`.
This required a change to `open_floating_preview` to work - previously if a provider returned a bufnr only, `open_floating_preview` would read in all the lines from the buffer and then set them again using `nvim_buf_set_lines`. This is both unnecessary and causes problems, such as breaking applied highlights in the case of diagnostics. `open_floating_preview` will now only set the buffer's lines if they are explicitly provided through the `contents` parameter.
Resolves #34

feat: add diagnostic provider

---

README.md
lua/hover/providers/highlight.lua

Reused code from [`vim.show_pos`](https://github.com/neovim/neovim/blob/20a7eebec086129e605041d32916f36df50890de/runtime/lua/vim/_inspector.lua#L152). Tried to override `vim.api.nvim_echo`, but it is extremely unsafe and messed up gui a bit. Then I tried to capture output of the command into buffer but that droped highlights.
I use `vim.o.cmdheight = 0` and status bar blinks. Looks like something is blocking gui. Leaving it as draft until I figure out why.

feat: add highlight provider

---

lua/hover/actions.lua
lua/hover/providers.lua
lua/hover/providers/diagnostic.lua
lua/hover/providers/fold_preview.lua

Fixes #73
Now diagnostic and fold preview show information from under the mouse on hover, not under the cursor.
I haven't changed the other providers (which also have this bug) since they depend on the cursor to get information (i.e. `<cword>`). Those could require a larger refactor.
More generally, all providers seem to only work with the current window, whereas, in a window split, the current window might not be the window the mouse is hovering on, returning wrong information. Fixing this would be best done in a separate PR as the changes would be quite large.
So, for this PR, I try to bring the most value for the smallest changes. Let me know if any further changes are needed.

Use mouse position for diagnostic and fold preview

---

lua/hover/util.lua

Fixes #76, possibly fixes #70, #33 as well
Copies the Nvim 0.10.4 implementation for syntax highlighting on the hover window in order to use treesitter.
Before:
After:

Fix missing treesitter highlighting on hover window

---

README.md

This seemed like a small oversight.

Fix highlight provider name in README

---

lua/hover/providers/gh.lua
lua/hover/providers/gh_user.lua

Thanks for this nice plugin!
The recent migration to the new async framework in https://github.com/lewis6991/hover.nvim/commit/fdc5b4fc3f5300c87fbde16cab0aeb122ba6324a missed two minor adjustments.
This causes two issues:
1. The `gh` provider crashes when querying issues for the current repository since `vim.system` receives the callback in place of `cmd`:
> vim/\_system.lua:330: cmd: expected table, got function
2. Both `gh` and `gh_users` providers always run the `gh` CLI in nvim's `current-directory`, not the directory that contains the current buffer. This can cause missing/wrong issues to be returned. Unsure about the impact on `gh_users`.
Hope submitting this is fine and I did everything correctly. Cheers!

fix(providers): Fix crash, respect buffer repository

---

README.md
lua/hover.lua
lua/hover/actions.lua
lua/hover/highlights.lua
lua/hover/providers/diagnostic.lua
lua/hover/util.lua

This adds custom highlight groups for the hover window, and aliases them to the highlights used previously. With this patch, a user can create custom styles for the hover window that don't affect any other hover windows. With no customizations, it should look identical to before, with one exception: I switched the background of the source bar (`HoverSourceLine`) to use `TabLine` instead of `Normal`.
For the highlight names, I just picked what that felt right, but they could probably be improved. Additionally, `HoverSourceLine` could reasonably be `FloatTitle`, `TabLine`, or `WinBar`, but I picked `TabLine` since sources already use `TabLineSel` and `TabLineFill`.

Add custom highlight groups

---

README.md

Replace deprecated function calls with their current equivalents:
- hover_switch() -> switch()
- setup() -> config()
These changes ensure the documentation reflects the current recommended API usage.

docs: update README to use current API instead of deprecated functions
